export type CommissioningChecklistFieldKey =
  | 'job_reference'
  | 'commissioning_date'
  | 'next_service_due'
  | 'engineer_name'
  | 'company_name'
  | 'company_address_line1'
  | 'company_address_line2'
  | 'company_address_city'
  | 'company_postcode'
  | 'company_tel'
  | 'gas_safe_number'
  | 'engineer_id_card_number'
  | 'job_address_name'
  | 'job_address_line1'
  | 'job_address_line2'
  | 'job_address_city'
  | 'job_postcode'
  | 'job_tel'
  | 'client_name'
  | 'client_company'
  | 'client_address_line1'
  | 'client_address_line2'
  | 'client_address_city'
  | 'client_postcode'
  | 'client_tel'
  | 'appliance_type'
  | 'appliance_make'
  | 'appliance_model'
  | 'appliance_location'
  | 'appliance_serial'
  | 'gc_number'
  | 'landlord_equipment'
  | 'flue_type'
  | 'heat_input'
  | 'running_set_point_temp'
  | 'safety_devices'
  | 'ventilation'
  | 'high_combustion_co_ppm'
  | 'high_combustion_co2'
  | 'high_combustion_ratio'
  | 'low_combustion_co_ppm'
  | 'low_combustion_co2'
  | 'low_combustion_ratio'
  | 'gas_rate'
  | 'gas_tightness'
  | 'equipotential_earth_bonding'
  | 'gas_meter_pressure'
  | 'inlet_test_point_pressure'
  | 'max_rate_gas_meter_pressure'
  | 'inlet_test_point_max_rate_pressure'
  | 'engineer_comments'
  | 'print_name_issued'
  | 'print_name_received';

export const COMMISSIONING_CHECKLIST_FIELD_MAP: Record<CommissioningChecklistFieldKey, string> = {
  job_reference: 'cert_no',
  commissioning_date: 'commissioning_date',
  next_service_due: 'next_service_due',
  engineer_name: 'company.engineer',
  company_name: 'company.company',
  company_address_line1: 'company.address_line_1',
  company_address_line2: 'company.address_line_2',
  company_address_city: 'company.address_line_3',
  company_postcode: 'company.post_code',
  company_tel: 'company.tel_no',
  gas_safe_number: 'company.gas_safe_reg',
  engineer_id_card_number: 'company.id_card_no',
  job_address_name: 'job_address.name',
  job_address_line1: 'job_address.address_line_1',
  job_address_line2: 'job_address.address_line_2',
  job_address_city: 'job_address.address_line_3',
  job_postcode: 'job_address.post_code',
  job_tel: 'job_address.tel-no',
  client_name: 'customer.name',
  client_company: 'customer.company',
  client_address_line1: 'customer.address_line_1',
  client_address_line2: 'customer.address_line_2',
  client_address_city: 'customer.address_line_3',
  client_postcode: 'customer.post_code',
  client_tel: 'customer.tel_no',
  appliance_type: 'appliance_type',
  appliance_make: 'appliance_make',
  appliance_model: 'appliance_model',
  appliance_location: 'appliance_location',
  appliance_serial: 'serial_no',
  gc_number: 'gc_number',
  landlord_equipment: 'landlord_equipment',
  flue_type: 'flue_type',
  heat_input: 'heat_input',
  running_set_point_temp: 'running_set_point_temp',
  safety_devices: 'safety_devices',
  ventilation: 'ventilation',
  high_combustion_co_ppm: 'high_combustion.co_ppm',
  high_combustion_co2: 'high_combustion.co2',
  high_combustion_ratio: 'high_combustion.co_co2',
  low_combustion_co_ppm: 'low_combustion.co_ppm',
  low_combustion_co2: 'low_combustion.co2',
  low_combustion_ratio: 'low_combustion.co_co2',
  gas_rate: 'gas_rate',
  gas_tightness: 'gas_tightness',
  equipotential_earth_bonding: 'equipotential_earth_bonding',
  gas_meter_pressure: 'gas_meter_pressure',
  inlet_test_point_pressure: 'inlet_test_point_pressure',
  max_rate_gas_meter_pressure: 'max_rate_gas_meter_pressure',
  inlet_test_point_max_rate_pressure: 'inlet_test_point_max_rate_pressure',
  engineer_comments: 'engineers_comments',
  print_name_issued: 'print_name_issued',
  print_name_received: 'print_name_received',
};
