export type GasBreakdownFieldKey =
  | 'job_reference'
  | 'job_visit_date'
  | 'job_address_name'
  | 'job_address_line1'
  | 'job_address_line2'
  | 'job_address_city'
  | 'job_postcode'
  | 'job_tel'
  | 'client_name'
  | 'client_company'
  | 'client_address_line1'
  | 'client_address_line2'
  | 'client_city'
  | 'client_postcode'
  | 'client_tel'
  | 'client_email'
  | 'landlord_name'
  | 'landlord_address'
  | 'engineer_name'
  | 'company_name'
  | 'company_address_line1'
  | 'company_address_line2'
  | 'company_city'
  | 'company_postcode'
  | 'company_tel'
  | 'gas_safe_number'
  | 'engineer_id_card_number'
  | 'appliance_type'
  | 'appliance_make'
  | 'appliance_model'
  | 'appliance_location'
  | 'appliance_serial'
  | 'combustion_co'
  | 'combustion_co2'
  | 'combustion_ratio'
  | 'safety_operating_correctly'
  | 'safety_conforms_standards'
  | 'safety_notice_explained'
  | 'safety_controls_checked'
  | 'operating_pressure'
  | 'heat_input'
  | 'flueing_safe'
  | 'ventilation_safe'
  | 'combustion_test'
  | 'burner_pressure_correct'
  | 'tightness_test'
  | 'fault_location'
  | 'part_fitted'
  | 'fault_resolved'
  | 'parts_required'
  | 'advice_appliance_safe'
  | 'advice_system_improvements'
  | 'advice_all_parts_available'
  | 'advice_replacement_recommended'
  | 'advice_magnetic_filter'
  | 'advice_co_alarm'
  | 'breakdown_summary'
  | 'advice_summary'
  | 'engineer_comments'
  | 'issued_by_name'
  | 'received_by_name';

export const GAS_BREAKDOWN_FIELD_MAP: Record<GasBreakdownFieldKey, string> = {
  job_reference: 'Cert No',
  job_visit_date: 'Date',
  client_name: '1',
  client_company: '2',
  client_address_line1: '3',
  client_address_line2: '4',
  client_city: '5',
  client_postcode: '6',
  client_tel: '7',
  client_email: '8',
  landlord_name: '9',
  landlord_address: '10',
  job_address_name: '33',
  job_address_line1: '34',
  job_address_line2: '35',
  job_address_city: '36',
  job_postcode: '37',
  job_tel: '38',
  engineer_id_card_number: '39',
  engineer_name: '11',
  company_name: '12',
  company_address_line1: '13',
  company_address_line2: '14',
  company_city: '15',
  company_postcode: '16',
  company_tel: '17',
  gas_safe_number: '18',
  appliance_type: '19',
  appliance_make: '20',
  appliance_model: '21',
  appliance_location: '22',
  appliance_serial: '23',
  combustion_co: '24',
  combustion_co2: '25',
  combustion_ratio: '26',
  safety_operating_correctly: '27',
  safety_conforms_standards: '28',
  safety_notice_explained: '29',
  safety_controls_checked: '30',
  operating_pressure: '31',
  heat_input: '32',
  flueing_safe: '40',
  ventilation_safe: '41',
  combustion_test: '42',
  burner_pressure_correct: '43',
  tightness_test: '44',
  fault_location: '45',
  part_fitted: '46',
  fault_resolved: '47',
  parts_required: '48',
  advice_appliance_safe: '49',
  advice_system_improvements: '50',
  advice_all_parts_available: '51',
  advice_replacement_recommended: '52',
  advice_magnetic_filter: '53',
  advice_co_alarm: '54',
  breakdown_summary: '55',
  advice_summary: '56',
  engineer_comments: 'Engineer Comments',
  issued_by_name: 'undefined',
  received_by_name: 'undefined_2',
};
